# Generated by Django 3.0.7 on 2020-06-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(blank=True, null=True)),
                ('nickname', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('subboardnum', models.IntegerField(blank=True, db_column='subBoardNum', null=True)),
            ],
            options={
                'db_table': 'notice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.TextField(blank=True, null=True)),
                ('language', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'study',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subboard',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('registernickname', models.TextField(blank=True, db_column='registerNickname', null=True)),
                ('requestnickname', models.TextField(blank=True, db_column='requestNickname', null=True)),
                ('language', models.TextField(blank=True, null=True)),
                ('contents', models.TextField(blank=True, null=True)),
                ('tax', models.IntegerField(blank=True, null=True)),
                ('time', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subBoard',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.TextField(blank=True, null=True)),
                ('password', models.TextField(blank=True, null=True)),
                ('nickname', models.TextField(blank=True, null=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('money', models.IntegerField(blank=True, null=True)),
                ('requestnum', models.IntegerField(blank=True, db_column='requestNum', null=True)),
                ('registernum', models.IntegerField(blank=True, db_column='registerNum', null=True)),
                ('ratingcompleteness', models.FloatField(blank=True, db_column='ratingCompleteness', null=True)),
                ('ratingclarity', models.FloatField(blank=True, db_column='ratingClarity', null=True)),
                ('ratingtime', models.FloatField(blank=True, db_column='ratingTime', null=True)),
                ('noticecnt', models.IntegerField(blank=True, db_column='noticeCnt', null=True)),
            ],
            options={
                'db_table': 'userInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.CharField(max_length=10)),
            ],
        ),
    ]
